const testDataAgency = [
  {
    data: [
      {
        id: 6207,
        friend_id: 6316,
        avatar: {
          additional_info: {
            sizes: ['small_icon', 'middle_icon', 'big_icon', 'avatar', 'avatar_icon', 'avatar_profile'],
            size_urls: {
              small_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/small.png',
              middle_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/middle.png',
              big_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/big.png',
              avatar: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar.png',
              avatar_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_icon.png',
              avatar_profile:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_profile.png',
            },
          },
          filename: 'original',
          original_filename: 'original.png',
          url: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/original.png',
          token: null,
        },
        email: '',
        contacts: {
          is_company: true,
          is_same_hometown: false,
          note: null,
          company: 'asd',
          phones: [
            {
              type: 'work',
              value: '17739681681',
              country: 'us',
            },
          ],
          emails: [
            {
              type: 'work',
              value: 'www.com.ua@gmail.com',
            },
          ],
          socials: [
            {
              type: 'instagam',
              value: 'instagram.po.sto.gramm',
            },
          ],
          urls: [
            {
              type: 'work',
              value: 'www.com.ua',
            },
          ],
          addresses: [
            {
              type: 'hometown',
              map: {
                lat: 28.5709844,
                lng: 77.0718536,
              },
              address: 'H3CC+9PX, Bagdola, Sector 8 Dwarka, Dwarka, sdsds, Delhi 110077, Индия',
            },
            {
              type: 'current',
              map: {
                lat: 28.5709844,
                lng: 77.0718536,
              },
              address: 'H3CC+9PX, Bagdola, Sector 8 Dwarka, Dwarka, sdsds, Delhi 110077, Индия',
            },
            {
              type: 'school',
              map: {
                lat: 28.5709844,
                lng: 77.0718536,
              },
              address: 'H3CC+9PX, Bagdola, Sector 8 Dwarka, Dwarka, sdsds, Delhi 110077, Индия',
            },
            {
              type: 'other',
              map: {
                lat: 28.5709844,
                lng: 77.0718536,
              },
              address: 'H3CC+9PX, Bagdola, Sector 8 Dwarka, Dwarka, sdsds, Delhi 110077, Индия',
            },
          ],
        },
        phone: null,
        tag: [],
        first_name: 'asfasf',
        last_name: 'Asfasf',
        middle_name: null,
        birth_day: '2008-12-12',
        gender: 'Asd',
        data: null,
        role: null,
        description: null,
        note: 'note',
        user_id: 5521,
        sender_id: 5521,
        recipient_id: 6316,
        entity_type: 'contact',
        canceled_at: null,
        is_invited: false,
        chat_id: null,
        full_name: 'asfasf Asfasf',
        is_resend: false,
        company: null,
        documents: [],
      },
      {
        id: 6205,
        friend_id: 6312,
        avatar: {
          additional_info: {
            sizes: ['small_icon', 'middle_icon', 'big_icon', 'avatar', 'avatar_icon', 'avatar_profile'],
            size_urls: {
              small_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/small.png',
              middle_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/middle.png',
              big_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/big.png',
              avatar: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar.png',
              avatar_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_icon.png',
              avatar_profile:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_profile.png',
            },
          },
          filename: 'original',
          original_filename: 'original.png',
          url: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/original.png',
          token: null,
        },
        email: '',
        contacts: {
          is_company: false,
          is_same_hometown: false,
          note: null,
          company: null,
          phones: [],
          emails: [
            {
              type: 'home',
              value: 'dawd@gmail.com',
            },
          ],
          socials: [],
          urls: [],
          addresses: [],
        },
        phone: null,
        tag: [],
        first_name: 'dawdwa',
        last_name: 'dawdawdwa',
        middle_name: null,
        birth_day: null,
        gender: null,
        data: null,
        role: 'Friend',
        description: null,
        note: null,
        user_id: 5521,
        sender_id: 5521,
        recipient_id: 6312,
        entity_type: 'contact',
        canceled_at: null,
        is_invited: false,
        chat_id: null,
        full_name: 'dawdwa dawdawdwa',
        is_resend: false,
        company: null,
        documents: [],
      },
      {
        id: 6203,
        friend_id: 6307,
        avatar: {
          additional_info: {
            sizes: ['small_icon', 'middle_icon', 'big_icon', 'avatar', 'avatar_icon', 'avatar_profile'],
            size_urls: {
              small_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/small.png',
              middle_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/middle.png',
              big_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/big.png',
              avatar: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar.png',
              avatar_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_icon.png',
              avatar_profile:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_profile.png',
            },
          },
          filename: 'original',
          original_filename: 'original.png',
          url: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/original.png',
          token: null,
        },
        email: '',
        contacts: {
          is_company: false,
          is_same_hometown: false,
          note: null,
          company: 'vxcvxcv',
          phones: [],
          emails: [
            {
              type: 'work',
              value: 'daddaw@gmail.com',
            },
          ],
          socials: [],
          urls: [],
          addresses: [],
        },
        phone: null,
        tag: [],
        first_name: 'kjdawdawdw',
        last_name: 'cxz',
        middle_name: null,
        birth_day: null,
        gender: null,
        data: null,
        role: 'Friend',
        description: null,
        note: null,
        user_id: 5521,
        sender_id: 5521,
        recipient_id: 6307,
        entity_type: 'contact',
        canceled_at: null,
        is_invited: false,
        chat_id: null,
        full_name: 'kjdawdawdw cxz',
        is_resend: false,
        company: null,
        documents: [],
      },
      {
        id: 6202,
        friend_id: 6306,
        avatar: {
          additional_info: {
            sizes: ['small_icon', 'middle_icon', 'big_icon', 'avatar', 'avatar_icon', 'avatar_profile'],
            size_urls: {
              small_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/small.png',
              middle_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/middle.png',
              big_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/big.png',
              avatar: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar.png',
              avatar_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_icon.png',
              avatar_profile:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_profile.png',
            },
          },
          filename: 'original',
          original_filename: 'original.png',
          url: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/original.png',
          token: null,
        },
        email: '',
        contacts: {
          is_company: false,
          is_same_hometown: false,
          note: null,
          company: null,
          phones: [
            {
              type: 'work',
              value: '+380666502266',
              country: 'UA',
            },
          ],
          emails: [],
          socials: [],
          urls: [],
          addresses: [],
        },
        phone: null,
        tag: [],
        first_name: 'meet',
        last_name: 'meet',
        middle_name: null,
        birth_day: null,
        gender: null,
        data: null,
        role: 'Friend',
        description: null,
        note: null,
        user_id: 5521,
        sender_id: 5521,
        recipient_id: 6306,
        entity_type: 'contact',
        canceled_at: null,
        is_invited: false,
        chat_id: null,
        full_name: 'meet meet',
        is_resend: false,
        company: null,
        documents: [],
      },
      {
        id: 6199,
        friend_id: 6303,
        avatar: {
          additional_info: {
            sizes: ['small_icon', 'middle_icon', 'big_icon', 'avatar', 'avatar_icon', 'avatar_profile'],
            size_urls: {
              small_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/small.png',
              middle_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/middle.png',
              big_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/big.png',
              avatar: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar.png',
              avatar_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_icon.png',
              avatar_profile:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_profile.png',
            },
          },
          filename: 'original',
          original_filename: 'original.png',
          url: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/original.png',
          token: null,
        },
        email: '',
        contacts: {
          is_company: false,
          is_same_hometown: false,
          note: null,
          company: null,
          phones: [],
          emails: [
            {
              type: 'home',
              value: 'вфцвцф@gmail.com',
            },
          ],
          socials: [],
          urls: [],
          addresses: [],
        },
        phone: null,
        tag: [],
        first_name: 'контакт',
        last_name: 'вцфвцф',
        middle_name: null,
        birth_day: null,
        gender: null,
        data: null,
        role: 'Friend',
        description: null,
        note: null,
        user_id: 5521,
        sender_id: 5521,
        recipient_id: 6303,
        entity_type: 'contact',
        canceled_at: null,
        is_invited: false,
        chat_id: null,
        full_name: 'контакт вцфвцф',
        is_resend: false,
        company: null,
        documents: [],
      },
      {
        id: 6197,
        friend_id: 6300,
        avatar: {
          additional_info: {
            sizes: ['small_icon', 'middle_icon', 'big_icon', 'avatar', 'avatar_icon', 'avatar_profile'],
            size_urls: {
              small_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/small.png',
              middle_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/middle.png',
              big_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/big.png',
              avatar: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar.png',
              avatar_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_icon.png',
              avatar_profile:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_profile.png',
            },
          },
          filename: 'original',
          original_filename: 'original.png',
          url: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/original.png',
          token: null,
        },
        email: '',
        contacts: {
          is_company: false,
          is_same_hometown: false,
          note: null,
          company: null,
          phones: [],
          emails: [
            {
              type: 'personal',
              value: 'vonu.yskravi@gmail.com',
            },
          ],
          socials: [],
          urls: [],
          addresses: [],
        },
        phone: '+380666509988',
        tag: [],
        first_name: 'Test',
        last_name: 'QA',
        middle_name: 'jljsadj',
        birth_day: '2009-03-01',
        gender: 'male',
        data: null,
        role: 'Friend',
        description: null,
        note: null,
        user_id: 5521,
        sender_id: 5521,
        recipient_id: 6300,
        entity_type: 'contact',
        canceled_at: null,
        is_invited: false,
        chat_id: null,
        full_name: 'Test QA',
        is_resend: false,
        company: null,
        documents: [],
      },
      {
        id: 5911,
        friend_id: 6152,
        avatar: {
          additional_info: {
            sizes: ['small_icon', 'middle_icon', 'big_icon', 'avatar', 'avatar_icon', 'avatar_profile'],
            size_urls: {
              small_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/small.png',
              middle_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/middle.png',
              big_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/big.png',
              avatar: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar.png',
              avatar_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_icon.png',
              avatar_profile:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_profile.png',
            },
          },
          filename: 'original',
          original_filename: 'original.png',
          url: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/original.png',
          token: null,
        },
        email: '',
        contacts: {
          is_company: false,
          is_same_hometown: false,
          note: null,
          company: null,
          phones: [
            {
              type: 'personal',
              value: '+380923232312',
              country: 'UA',
            },
          ],
          emails: [
            {
              type: 'personal',
              value: 'glasoowe@mail.com',
            },
          ],
          socials: [],
          urls: [],
          addresses: [],
        },
        phone: null,
        tag: [],
        first_name: 'Mukola',
        last_name: 'Kutsil',
        middle_name: null,
        birth_day: null,
        gender: null,
        data: null,
        role: 'Friend',
        description: null,
        note: null,
        user_id: 5521,
        sender_id: 5521,
        recipient_id: 6152,
        entity_type: 'contact',
        canceled_at: null,
        is_invited: false,
        chat_id: null,
        full_name: 'Mukola Kutsil',
        is_resend: true,
        company: null,
        documents: [],
      },
      {
        id: 5910,
        friend_id: 6151,
        avatar: {
          additional_info: {
            sizes: ['small_icon', 'middle_icon', 'big_icon', 'avatar', 'avatar_icon', 'avatar_profile'],
            size_urls: {
              small_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/small.png',
              middle_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/middle.png',
              big_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/big.png',
              avatar: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar.png',
              avatar_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_icon.png',
              avatar_profile:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_profile.png',
            },
          },
          filename: 'original',
          original_filename: 'original.png',
          url: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/original.png',
          token: null,
        },
        email: 'vonu.yskravi@gmail.com',
        contacts: {
          is_company: false,
          is_same_hometown: false,
          note: null,
          company: null,
          phones: [],
          emails: [
            {
              type: 'personal',
              value: 's.kushnerov@hubmee.com',
            },
          ],
          socials: [],
          urls: [],
          addresses: [],
        },
        phone: '+380663554433',
        tag: [],
        first_name: 'vonu',
        last_name: 'yskravi',
        middle_name: null,
        birth_day: '2010-02-09',
        gender: 'male',
        data: null,
        role: 'Friend',
        description: null,
        note: null,
        user_id: 5521,
        sender_id: 5521,
        recipient_id: 6151,
        entity_type: 'contact',
        canceled_at: null,
        is_invited: false,
        chat_id: null,
        full_name: 'vonu yskravi',
        is_resend: false,
        company: null,
        documents: [],
      },
      {
        id: 5680,
        friend_id: 5880,
        avatar: {
          additional_info: {
            sizes: ['small_icon', 'middle_icon', 'big_icon', 'avatar', 'avatar_icon', 'avatar_profile'],
            size_urls: {
              small_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/small.png',
              middle_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/middle.png',
              big_icon: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/big.png',
              avatar: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar.png',
              avatar_icon:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_icon.png',
              avatar_profile:
                'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/avatar_profile.png',
            },
          },
          filename: 'original',
          original_filename: 'original.png',
          url: 'https://hubmee-test-spaces.fra1.digitaloceanspaces.com/default/contact/original.png',
          token: null,
        },
        email: '',
        contacts: {
          is_company: false,
          is_same_hometown: false,
          note: null,
          company: 'types',
          phones: [
            {
              type: 'personal',
              value: '+380951223322',
              country: 'UA',
            },
          ],
          emails: [
            {
              type: 'home',
              value: 'qweeweq@qweqwe.com',
            },
          ],
          socials: [],
          urls: [],
          addresses: [],
        },
        phone: null,
        tag: [],
        first_name: 'Galla',
        last_name: 'Seee',
        middle_name: null,
        birth_day: '2010-07-09',
        gender: 'male',
        data: null,
        role: 'Friend',
        description: null,
        note: null,
        user_id: 5521,
        sender_id: 5521,
        recipient_id: 5880,
        entity_type: 'contact',
        canceled_at: null,
        is_invited: false,
        chat_id: null,
        full_name: 'Galla Seee',
        is_resend: true,
        company: null,
        documents: [],
      },
    ],
    links: {
      first: 'http://test.user.hubmee.org/connections/contacts?page=1&query=',
      last: 'http://test.user.hubmee.org/connections/contacts?page=1&query=',
      prev: null,
      next: null,
    },
    meta: {
      current_page: 1,
      from: 1,
      last_page: 1,
      links: [
        {
          url: null,
          label: '&laquo; Previous',
          active: false,
        },
        {
          url: 'http://test.user.hubmee.org/connections/contacts?page=1',
          label: '1',
          active: true,
        },
        {
          url: null,
          label: 'Next &raquo;',
          active: false,
        },
      ],
      path: 'http://test.user.hubmee.org/connections/contacts',
      per_page: 15,
      to: 9,
      total: 9,
    },
  },
];

export const MOCK_DATA = {
  testDataAgency,
};
