export enum STEP_CASE {
  CHANGE_PLAN = 'CHANGE_PLAN',
  FEEDBACK = 'FEEDBACK',
  BOOK_A_DEMO = 'BOOK_A_DEMO',
  SUCCESS_BOOK = 'SUCCESS_BOOK',
  TOO_MUCH = 'TOO_MUCH',
  DISCOUNT_OFFER = 'DISCOUNT_OFFER',
  CANCELED = 'CANCELED',
}
