import { testFiles } from './testMedia.enum';

export const testGarageItem = {
  id: 1885,
  is_shared: true,
  is_personal: false,
  permission: 'view',
  transport_type: 'Car',
  year: 2018,
  license_plate: 'INS-213115142262DF',
  make: 'Mazda',
  model: '3',
  user: {
    id: 1286,
    is_fake: false,
    gender: 'male',
    first_name: 'Vasyl',
    middle_name: null,
    last_name: 'Danilyuk',
    email: 'vasyl@hubmee.com',
    phone: null,
    birth_day: '1999-02-12',
    relationship_status: 'Married',
    default_package_id: 1,
    timezone_name: 'Europe/Kiev',
    timezone: '+03:00',
    unverified_login: {
      phone: null,
      email: null,
    },
    last_activated_at: '2022-09-03 13:56:52',
    activated_at: '2021-10-27 12:11:07',
    deleted_at: null,
    avatar: null,
    role: null,
    package: null,
    background: null,
    gallery: null,
    documents: null,
    appearanceValue: null,
    bodyArt: null,
    avatars: null,
    full_name: 'Vasyl Danilyuk',
  },
  shared_users: [
    {
      id: 1286,
      full_name: 'Vasyl Danilyuk',
      first_name: 'Vasyl',
      last_name: 'Danilyuk',
      avatar: null,
      permission: 'owner',
      connection_role: 'Parent',
      entity_type: 'friend',
    },
    {
      id: 1427,
      full_name: 'Alyona Pavliuk',
      first_name: 'Alyona',
      last_name: 'Pavliuk',
      avatar: null,
      permission: 'view',
      connection_role: 'friend',
      entity_type: 'friend',
    },
    {
      id: 1678,
      full_name: 'Eliza Dubey',
      first_name: 'Eliza',
      last_name: 'Dubey',
      avatar: null,
      permission: 'view',
      connection_role: 'friend',
      entity_type: 'friend',
    },
    {
      id: 1279,
      full_name: 'Mila Petrenko',
      first_name: 'Mila',
      last_name: 'Petrenko',
      avatar: null,
      permission: 'view',
      connection_role: 'friend',
      entity_type: 'friend',
    },
    {
      id: 1280,
      full_name: 'Mykola Kutsil',
      first_name: 'Mykola',
      last_name: 'Kutsil',
      avatar: null,
      permission: 'view',
      connection_role: 'Friend',
      entity_type: 'friend',
    },
    {
      id: 1278,
      full_name: 'Roman Petrenko',
      first_name: 'Roman',
      last_name: 'Petrenko',
      avatar: null,
      permission: 'view',
      connection_role: 'Grandfather',
      entity_type: 'friend',
    },
    {
      id: 1281,
      full_name: 'Stas Khort',
      first_name: 'Stas',
      last_name: 'Khort',
      avatar: null,
      permission: 'view',
      connection_role: 'friend',
      entity_type: 'friend',
    },
    {
      id: 23,
      full_name: 'Vitaliy Ivanyshyn',
      first_name: 'Vitaliy',
      last_name: 'Ivanyshyn',
      avatar: null,
      permission: 'view',
      connection_role: 'Sister',
      entity_type: 'friend',
    },
    {
      id: 1282,
      full_name: 'Ivan Vlasenko',
      first_name: 'Ivan',
      last_name: 'Vlasenko',
      avatar: null,
      permission: 'view',
      connection_role: null,
      entity_type: null,
    },
    {
      id: 1645,
      full_name: 'Solya Nasimuk',
      first_name: 'Solya',
      last_name: 'Nasimuk',
      avatar: null,
      permission: 'view',
      connection_role: 'Friend',
      entity_type: 'friend',
    },
  ],
  expiration_block: {
    label: 'insurance',
    name: 'USG',
    expiration: '2023-04-14',
  },
  photos: [
    {
      id: 23940,
      filename: 'original',
      original_filename: '20220718_1134.jpeg',
      token: '',
      additional_info: {
        sizes: ['big_icon', 'middle_icon', 'gallery'],
        size_urls: {
          big_icon: '/storage/transport_photo/2022/07/18/HDD8HOPuhNZlpqGj/big_icon.jpeg',
          middle_icon: '/storage/transport_photo/2022/07/18/HDD8HOPuhNZlpqGj/middle_icon.jpeg',
          gallery: '/storage/transport_photo/2022/07/18/HDD8HOPuhNZlpqGj/gallery.jpeg',
        },
        in_progress: true,
      },
      created_at: '2022-07-18 08:34:19',
      url: '/storage/transport_photo/2022/07/18/HDD8HOPuhNZlpqGj/original.jpeg',
    },
  ],
  documents: { all: [], insurances: [] },
  insuranceImage: testFiles,
};
