const userData = {
  id: 5905,
  friend_id: 5930,
  avatar: 'Kolla',
  email: 'hwfbwj@gmail.com',
  contacts: null,
  phone: null,
  tag: [],
  first_name: 'Ira',
  last_name: 'Vor',
  middle_name: null,
  birth_day: null,
  gender: 'female',
  data: null,
  role: 'Friend',
  description: null,
  note: null,
  user_id: 5521,
  sender_id: 5521,
  recipient_id: 5930,
  entity_type: 'outgoing',
  canceled_at: null,
  is_invited: false,
  chat_id: null,
  full_name: 'Ira Vor',
  is_resend: false,
  company: 'Hubme',
  documents: [],
};

const userDataArray = [
  {
    id: 5904,
    friend_id: 5128,
    avatar: null,
    email: 'rozrobnyk@hubmee.com',
    contacts: null,
    phone: null,
    tag: [],
    first_name: 'Devops',
    last_name: 'Rozrobnyk',
    middle_name: null,
    birth_day: null,
    gender: null,
    data: null,
    role: 'Friend',
    description: null,
    note: null,
    user_id: 5521,
    sender_id: 5521,
    recipient_id: 5128,
    entity_type: 'outgoing',
    canceled_at: null,
    is_invited: false,
    chat_id: null,
    full_name: 'Devops Rozrobnyk',
    is_resend: false,
    company: null,
    documents: [],
  },
  {
    id: 5902,
    friend_id: 4785,
    avatar: null,
    email: 'vonu.yskravi@gmail.com',
    contacts: {
      is_company: false,
      is_same_hometown: false,
      note: null,
      company: null,
      phones: [],
      emails: [
        {
          type: 'personal',
          value: 'vonu.yskravi@gmail.com',
        },
      ],
      socials: [],
      urls: [],
      addresses: [],
    },
    phone: '+380663554433',
    tag: [],
    first_name: 'vonu',
    last_name: 'yskravi',
    middle_name: null,
    birth_day: '2010-02-09',
    gender: 'male',
    data: null,
    role: 'Friend',
    description: null,
    note: null,
    user_id: 5521,
    sender_id: 5521,
    recipient_id: 4785,
    entity_type: 'friend',
    canceled_at: null,
    is_invited: false,
    chat_id: 1113,
    full_name: 'vonu yskravi',
    is_resend: false,
    company: null,
    documents: [],
  },
];

export const dataMenuList = {
  userData,
  userDataArray,
};
